### Libreria utilizada

In [1]:
import pandas as pd
import re

### Me traje los dos archivos

In [2]:
df1_modicado = pd.read_csv('movies.modificado.csv')
df_credits2_modi = pd.read_csv('credits.modificado.csv')

C:\Users\Luis Fernando Martin\AppData\Local\Temp\ipykernel_8524\1284184175.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df1_modicado = pd.read_csv('movies.modificado.csv')

### Converti los dos DataFrames en string para poderlos concatenar

In [3]:
# Convertir la columna 'id' a string en ambos DataFrames
df1_modicado['id'] = df1_modicado['id'].astype(str)
df_credits2_modi['id'] = df_credits2_modi['id'].astype(str)

### Hice la concatenacion de los dos DataFrames

In [4]:
#df_concat = pd.concat([df1_modicado, df_credits2_modi], axis=0, ignore_index=True)
df_unidos = df1_modicado.merge(df_credits2_modi, how='inner', on='id')

In [5]:
# Configuración para mostrar todas las columnas
pd.set_option('display.max_columns', None)

### Buscar los caracteres no alfabéticos

In [6]:
# Cree una función para verificar si el título contiene solo caracteres alfabéticos
def filtrar_titulo(titulo):
    # Verifique si el título contiene solo letras, números, espacios y otros caracteres específicos
    return re.match(r"^[a-zA-Z0-9\s\$\-\#\?\&\!\ñ\¿\¡]*$", titulo) is not None

# Filtre las filas donde el título de la película es válido en el DataFrame 'df1'
df_unidos = df_unidos[df_unidos['title'].apply(filtrar_titulo)]

# Mostrar los primeros registros para verificar el resultado
#df_unidos

In [7]:
# Converti todos los valores en la columna 'title' de 'df1' a cadenas
df_unidos['title'] = df_unidos['title'].astype(str)

# Filtre las filas donde el título de la película es válido
df_unidos= df_unidos[df_unidos['title'].apply(filtrar_titulo)]

# Mostrar los primeros registros para verificar el resultado
#df_unidos

In [8]:
# Verifique si las columnas existen y eliminarlas si es así
columns_to_drop = ['status', 'tagline', 'spoken_languages', 'production_countries']

# Eliminar las columnas si existen
df_unidos = df_unidos.drop(columns=[col for col in columns_to_drop if col in df_unidos.columns], errors='ignore')

# Mostrar el DataFrame para confirmar que las columnas han sido eliminadas
#df_unidos

In [14]:
df_unidos

,budget,genres,id,original_language,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,coll_id,coll_name,production_company_id,production_company_name,release_year,return,director_name,actor_names
0,30000000.0,"Animation, Comedy, Family",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033.0,81.0,Toy Story,7.7,5415.0,10194.0,Toy Story Collection,3.0,Pixar Animation Studios,1995.0,12.451801,John Lasseter,"['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim..."
1,65000000.0,"Adventure, Fantasy, Family",8844,en,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249.0,104.0,Jumanji,6.9,2413.0,sin dato,sin dato,559.0,TriStar Pictures,1995.0,4.043035,Joe Johnston,"['Robin Williams', 'Jonathan Hyde', 'Kirsten D..."
2,0.0,"Romance, Comedy",15602,en,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,0.0,101.0,Grumpier Old Men,6.5,92.0,119050.0,Grumpy Old Men Collection,6194.0,Warner Bros.,1995.0,0.000000,Howard Deutch,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret..."
3,16000000.0,"Comedy, Drama, Romance",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156.0,127.0,Waiting to Exhale,6.1,34.0,sin dato,sin dato,306.0,Twentieth Century Fox Film Corporation,1995.0,5.090760,Forest Whitaker,"['Whitney Houston', 'Angela Bassett', 'Loretta..."
4,0.0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911.0,106.0,Father of the Bride Part II,5.7,173.0,96871.0,Father of the Bride Collection,5842.0,Sandollar Productions,1995.0,0.000000,Charles Shyer,"['Steve Martin', 'Diane Keaton', 'Martin Short..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45340,0.0,"Drama, Action, Romance",30840,en,"Yet another version of the classic epic, with ...",5.683753,1991-05-13,0.0,104.0,Robin Hood,5.7,26.0,sin dato,sin dato,7025.0,Westdeutscher Rundfunk (WDR),1991.0,0.000000,John Irvin,"['Patrick Bergin', 'Uma Thurman', 'David Morri..."
45341,0.0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,2011-11-17,0.0,360.0,Century of Birthing,9.0,3.0,sin dato,sin dato,19653.0,Sine Olivia,2011.0,0.000000,Lav Diaz,"['Angel Aquino', 'Perry Dizon', 'Hazel Orencio..."
45342,0.0,"Action, Drama, Thriller",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0.0,90.0,Betrayal,3.8,6.0,sin dato,sin dato,6165.0,American World Pictures,2003.0,0.000000,Mark L. Lester,"['Erika Eleniak', 'Adam Baldwin', 'Julie du Pa..."
45343,0.0,sin dato,227506,en,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0.0,87.0,Satan Triumphant,0.0,0.0,sin dato,sin dato,88753.0,Yermoliev,1917.0,0.000000,Yakov Protazanov,"['Iwan Mosschuchin', 'Nathalie Lissenko', 'Pav..."
45344,0.0,sin dato,461257,en,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0.0,75.0,Queerama,0.0,0.0,sin dato,sin dato,sin dato,sin dato,2017.0,0.000000,Daisy Asquith,[]

In [21]:
# Guardar el DataFrame en un archivo CSV
df_unidos.to_csv('movies_credits3.csv', index=False)

In [13]:
df_unidos.isnull().sum()

budget                     0
genres                     0
id                         0
original_language          0
overview                   0
popularity                 0
release_date               0
revenue                    0
runtime                    0
title                      0
vote_average               0
vote_count                 0
coll_id                    0
coll_name                  0
production_company_id      0
production_company_name    0
release_year               0
return                     0
director_name              0
actor_names                0
dtype: int64

In [12]:
# Reemplazar valores NaN solo en las columnas que los contienen con 'sin dato'
df_unidos = df_unidos.apply(lambda x: x.fillna('sin dato') if x.isnull().any() else x)

In [16]:
# Convertir las columnas 'title', 'director_name', y 'actor_names' a tipo string
df_unidos['title'] = df_unidos['title'].astype(str)
df_unidos['director_name'] = df_unidos['director_name'].astype(str)
df_unidos['actor_names'] = df_unidos['actor_names'].astype(str)

# Verificar si las columnas fueron convertidas correctamente
print(df_unidos[['title', 'director_name', 'actor_names']].dtypes)

title            object
director_name    object
actor_names      object
dtype: object

In [20]:
# Verificar el tipo de la columna 'release_date'
print(df_unidos['release_date'].dtype)

datetime64[ns]

In [19]:
# Si es necesario, puedes convertir la columna a datetime
if df_unidos['release_date'].dtype != 'datetime64[ns]':
    df_unidos['release_date'] = pd.to_datetime(df_unidos['release_date'], errors='coerce')

In [22]:
df_unidos

,budget,genres,id,original_language,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,coll_id,coll_name,production_company_id,production_company_name,release_year,return,director_name,actor_names
0,30000000.0,"Animation, Comedy, Family",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033.0,81.0,Toy Story,7.7,5415.0,10194.0,Toy Story Collection,3.0,Pixar Animation Studios,1995.0,12.451801,John Lasseter,"['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim..."
1,65000000.0,"Adventure, Fantasy, Family",8844,en,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249.0,104.0,Jumanji,6.9,2413.0,sin dato,sin dato,559.0,TriStar Pictures,1995.0,4.043035,Joe Johnston,"['Robin Williams', 'Jonathan Hyde', 'Kirsten D..."
2,0.0,"Romance, Comedy",15602,en,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,0.0,101.0,Grumpier Old Men,6.5,92.0,119050.0,Grumpy Old Men Collection,6194.0,Warner Bros.,1995.0,0.000000,Howard Deutch,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret..."
3,16000000.0,"Comedy, Drama, Romance",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156.0,127.0,Waiting to Exhale,6.1,34.0,sin dato,sin dato,306.0,Twentieth Century Fox Film Corporation,1995.0,5.090760,Forest Whitaker,"['Whitney Houston', 'Angela Bassett', 'Loretta..."
4,0.0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911.0,106.0,Father of the Bride Part II,5.7,173.0,96871.0,Father of the Bride Collection,5842.0,Sandollar Productions,1995.0,0.000000,Charles Shyer,"['Steve Martin', 'Diane Keaton', 'Martin Short..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45340,0.0,"Drama, Action, Romance",30840,en,"Yet another version of the classic epic, with ...",5.683753,1991-05-13,0.0,104.0,Robin Hood,5.7,26.0,sin dato,sin dato,7025.0,Westdeutscher Rundfunk (WDR),1991.0,0.000000,John Irvin,"['Patrick Bergin', 'Uma Thurman', 'David Morri..."
45341,0.0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,2011-11-17,0.0,360.0,Century of Birthing,9.0,3.0,sin dato,sin dato,19653.0,Sine Olivia,2011.0,0.000000,Lav Diaz,"['Angel Aquino', 'Perry Dizon', 'Hazel Orencio..."
45342,0.0,"Action, Drama, Thriller",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0.0,90.0,Betrayal,3.8,6.0,sin dato,sin dato,6165.0,American World Pictures,2003.0,0.000000,Mark L. Lester,"['Erika Eleniak', 'Adam Baldwin', 'Julie du Pa..."
45343,0.0,sin dato,227506,en,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0.0,87.0,Satan Triumphant,0.0,0.0,sin dato,sin dato,88753.0,Yermoliev,1917.0,0.000000,Yakov Protazanov,"['Iwan Mosschuchin', 'Nathalie Lissenko', 'Pav..."
45344,0.0,sin dato,461257,en,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0.0,75.0,Queerama,0.0,0.0,sin dato,sin dato,sin dato,sin dato,2017.0,0.000000,Daisy Asquith,[]